"""empty message

Revision ID: 990a8ef43e86
Revises: 
Create Date: 2024-11-12 08:45:52.345726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '990a8ef43e86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('pickup_location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('display_image', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('negotiable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flairs', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('media', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year_of_manufacture', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('battery_life', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('storage_capacity', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('additional_details', sa.String(length=200), nullable=True))
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('validation_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validation_code_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('forget_pwd', sa.Enum('Unset', 'CodeSent', 'CodeVerified', name='forgetpasswordstate'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('forget_pwd')
        batch_op.drop_column('validation_code_expiration')
        batch_op.drop_column('validation_code')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('additional_details')
        batch_op.drop_column('storage_capacity')
        batch_op.drop_column('battery_life')
        batch_op.drop_column('material')
        batch_op.drop_column('weight')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('color')
        batch_op.drop_column('year_of_manufacture')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')
        batch_op.drop_column('media')
        batch_op.drop_column('flairs')
        batch_op.drop_column('negotiable')
        batch_op.drop_column('display_image')
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('datetime_created')

    # ### end Alembic commands ###
