import React from "react";
import { Navbar } from "../../components";
import { PageContainer, TermsHeading, TermsText, IntroText, EmailLink } from "./terms-of-use-page.styles";

const TermsOfUsePage = () => {
  return (
    <>
      <Navbar />
      <PageContainer>
        <TermsHeading>Terms of Use</TermsHeading>
        <IntroText>
          Welcome to our platform! These Terms of Use govern your access to and use of our second-hand marketplace. By using this platform, you agree to abide by these terms and conditions.
        </IntroText>
        <TermsText>
          <strong>1. Introduction</strong>
          <br />
          Our marketplace connects buyers and sellers of second-hand goods. The rules below apply to all users of the platform.
          <br /><br />
          <strong>2. User Responsibilities</strong>
          <br />
          - Provide accurate and honest information in listings and during registration.
          <br />
          - Do not post prohibited items (e.g., illegal, hazardous, or counterfeit goods).
          <br />
          - Respect other users and follow all applicable laws.
          <br /><br />
          <strong>3. Platform Responsibilities</strong>
          <br />
          - The platform facilitates transactions but does not guarantee the quality, legality, or condition of items.
          <br />
          - We are not liable for disputes between buyers and sellers.
          <br /><br />
          <strong>4. Account Management</strong>
          <br />
          - You are responsible for maintaining the confidentiality of your account details.
          <br />
          - Accounts may be suspended or terminated for violations of these terms.
          <br /><br />
          <strong>5. Liability Disclaimer</strong>
          <br />
          - We are not responsible for any losses or damages resulting from platform use.
          <br /><br />
          For further details, please contact us via{" "}
        <EmailLink
            href="mailto:uoft.markt@gmail.com?subject=Concerns About Terms Of Use"
            >
            contact us at uoft.markt@gmail.com
        </EmailLink>.
        </TermsText>
      </PageContainer>
    </>
  );
};

export { TermsOfUsePage };

// Note: These terms of use were generated by ChatGPT
