name: Frontend Coverage Test for Changed Files Only

on:
  pull_request:
    paths:
      - "markt-frontend/**"

jobs:
  frontend-pr-changes-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Run Full Test Coverage
        run: |
          npm run test-coverage | tee coverage_output.txt
        working-directory: markt-frontend

      - name: Filter Coverage Report for Changed Files
        if: success()
        run: |
          threshold=80
          echo "Identifying changed files and filtering coverage report:"
          fail=false
          changed_files=$(git diff --name-only origin/main HEAD | grep -E "\.js$|\.jsx$|\.ts$|\.tsx$")
          for file in $changed_files; do
            coverage=$(grep -A 1 "$file" coverage_output.txt | tail -n 1 | awk '{print $4}' | sed 's/%//')
            echo "$file: $coverage%"
            if (( $(echo "$coverage < $threshold" | bc -l) )); then
              fail=true
              echo "Code coverage for $file ($coverage%) is below the threshold ($threshold%)"
            fi
          done
          if [ "$fail" = true ]; then
            exit 1
          fi
        working-directory: markt-frontend

      - name: Upload Full Coverage Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: full-coverage-report
          path: markt-frontend/coverage/
