name: Coverage Check on PR

on:
  pull_request:
    paths:
      - "markt-frontend/**"

jobs:
  pr-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Run Tests with Coverage
        run: |
          npm run test-coverage | tee coverage_output.txt
        working-directory: markt-frontend

      - name: Get Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }} | grep "^markt-frontend/.*\\.tsx$" > changed_files.txt
        shell: bash

      - name: Filter Coverage for Changed Files
        run: |
          threshold=80
          failed=0
          while IFS= read -r file; do
            file_coverage=$(grep -oP "${file}\s*\|\s*\K[0-9]+\.[0-9]+" coverage_output.txt || echo "0")
            echo "Coverage for ${file}: $file_coverage%"
            if (( $(echo "$file_coverage < $threshold" | bc -l) )); then
              echo "Code coverage for ${file} ($file_coverage%) is below the threshold ($threshold%)."
              failed=1
            fi
          done < changed_files.txt
          if [ $failed -eq 1 ]; then
            echo "Some files do not meet the required coverage threshold. Failing the job."
            exit 1
          else
            echo "All changed files meet the required coverage threshold."
          fi
        shell: bash
        working-directory: markt-frontend

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: markt-frontend/coverage/
