name: Frontend PR Changes Test Coverage

on:
  push:

jobs:
  frontend-pr-changes-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Run Tests with Coverage
        run: |
          npm run test-coverage | tee coverage_output.txt
        working-directory: markt-frontend
