name: Coverage Check on PR

on:
  pull_request:
    paths:
      - "markt-frontend/**"

jobs:
  pr-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: get_changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- "markt-frontend/**" | grep '.tsx' | paste -sd "," -)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Run tests with coverage for changed files
        id: coverage_check
        if: steps.get_changed_files.outputs.changed_files
        run: |
          THRESHOLD=80
          if [[ -n "${{ steps.get_changed_files.outputs.changed_files }}" ]]; then
            npm run test-coverage -- --findRelatedTests ${{ steps.get_changed_files.outputs.changed_files }} > coverage_summary.txt || true
            COVERAGE=$(grep -oP '(?<=All files.*\s)\d+(?=%)' coverage_summary.txt | tail -1)
            echo "Coverage for changed files: $COVERAGE%"
            if [[ "$COVERAGE" -lt "$THRESHOLD" ]]; then
              echo "::set-output name=below_threshold::true"
            else
              echo "::set-output name=below_threshold::false"
            fi
          else
            echo "No TypeScript (.tsx) files changed in 'markt-frontend/'."
            echo "::set-output name=below_threshold::false"
          fi
        env:
          CI: true

      - name: Fail if below threshold
        if: steps.get_changed_files.outputs.changed_files && steps.coverage_check.outputs.below_threshold == 'true'
        run: exit 1
