name: Frontend Coverage Test for Changed Files Only

on:
  pull_request:
    paths:
      - "markt-frontend/**"

jobs:
  frontend-pr-changes-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Identify Changed Files and Run Test Coverage
        run: |
          threshold=80
          echo "Running full coverage and identifying changed files:"
          fail=false

          coverage_output=$(npm run test-coverage --silent --coverageReporters=text)
          echo "$coverage_output"

          changed_files=$(git diff --name-only origin/main HEAD | grep -E "\.js$|\.jsx$|\.ts$|\.tsx$" | xargs -n1 basename)

          for file in $changed_files; do
            coverage=$(echo "$coverage_output" | grep -A 1 "$file" | awk '/[0-9]+%/{gsub("%","",$4); print $4}')

            if [ -n "$coverage" ]; then
              echo "$file: $coverage%"
              if (( $(echo "$coverage < $threshold" | bc -l) )); then
                fail=true
                echo "Code coverage for $file ($coverage%) is below the threshold ($threshold%)"
              fi
            else
              echo "No coverage data found for $file."
            fi
          done
          if [ "$fail" = true ]; then
            exit 1
          fi
        working-directory: markt-frontend

      - name: Upload Full Coverage Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: full-coverage-report
          path: markt-frontend/coverage/
