name: Coverage Check on PR

on:
  pull_request:
    paths:
      - "markt-frontend/**"

jobs:
  pr-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Run tests with coverage for changed files
        run: |
          # Get changed files
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- "markt-frontend/**" | grep '.tsx' | paste -sd "," -)
          echo "Changed files: $CHANGED_FILES"

          # Set coverage threshold
          THRESHOLD=80

          # If there are changed files, run the tests
          if [[ -n "$CHANGED_FILES" ]]; then
            # Run test coverage on changed files only
            npm run test-coverage -- --findRelatedTests $CHANGED_FILES > coverage_summary.txt || true

            # Extract coverage percentage
            COVERAGE=$(grep -oP '(?<=All files.*\s)\d+(?=%)' coverage_summary.txt | tail -1)
            echo "Coverage for changed files: $COVERAGE%"
            
            # Fail if coverage is below threshold
            if [[ "$COVERAGE" -lt "$THRESHOLD" ]]; then
              echo "Test coverage is below the threshold of $THRESHOLD%."
              exit 1
            else
              echo "Test coverage meets the threshold of $THRESHOLD%."
            fi
          else
            echo "No TypeScript (.tsx) files changed in 'markt-frontend/'. Skipping coverage check."
          fi
        working-directory: markt-frontend
        env:
          CI: true
