name: Coverage Check on PR
on:
  pull_request:
    paths:
      - "markt-frontend/**"
jobs:
  pr-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: markt-frontend

      - name: Run Test Coverage
        run: |
          threshold=80
          fail=false

          npm run test-coverage --silent --coverageReporters=text > coverage_output.txt

          changed_files=$(git diff --name-only origin/main HEAD | grep -E "\.js$|\.jsx$|\.ts$|\.tsx$")

          for file in $changed_files; do
            coverage_line=$(grep -A 1 "$file" coverage_output.txt | tail -n 1)
            coverage=$(echo "$coverage_line" | awk '{gsub("%","",$4); print $4}')
            
            if [ -n "$coverage" ]; then
              echo "$file: $coverage%"
              if (( $(echo "$coverage < $threshold" | bc -l) )); then
                fail=true
                echo "Code coverage for $file ($coverage%) is below the threshold ($threshold%)"
              fi
            else
              echo "Skipping $file as no coverage data is found."
            fi
          done

          if [ "$fail" = true ]; then
            exit 1
          fi
        working-directory: markt-frontend

      - name: Upload Full Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-coverage-report
          path: markt-frontend/coverage/
